### ISSUE TITLE
Implement infinite scroll / auto-loading for list views

### ISSUE THREAD

**Issue by doughsay** [ambry-app/ambry#355]
Instead of requiring the user to click the "load more" link, let's automatically load more when scroll position reaches the bottom.

Some inspiration: https://elixircasts.io/infinite-scroll-with-liveview

List views that should be affected:

* [ ] Library recent books list
* [ ] Series books list
* [ ] Search results list

Lists that need some consideration:

These lists are embedded in pages with multiple lists and don't really have a good "scroll bottom".

* [ ] Continue Listening
* [ ] Authored / Narrated books

**Comment by lubien** [comment]
I'm taking a stab at this, can you assign me?
