### ISSUE TITLE
Unable to register initial user

### ISSUE THREAD

**Issue by GamerClassN7** [ambry-app/ambry#483]
After  initializing docker i get login screen, no
![image](https://user-images.githubusercontent.com/22167469/217258785-34c1f5d1-cf9b-488a-8a3c-11636e38edeb.png)
t registration screen as mentioned in reamde

**Comment by doughsay** [comment]
What image tag are you using?  `latest` or `main`?

**Comment by doughsay** [comment]
I know what the problem is, I'll be working on a fix.
